# Numpy Function

In [1]:
import os
os.getcwd()

'C:\\Users\\VISHNU KALE\\Desktop\\python july mid'

# 1. Array Creation

## 1. np.array()

In [ ]:
Create an array from Python lists/tuples.
Syntax: np.array(object, dtype=None)

In [2]:
arr = np.array([1, 2, 3])  #1D array from list
print(arr)

[1 2 3]


In [ ]:
arr = np.array([[1, 2], [3, 4]])  #2D array from nested list
print(arr)

## 2. np.zeros()

In [ ]:
 Create an array filled with 0s.
Syntax: np.zeros(shape, dtype=float)

In [3]:
arr = np.zeros((2, 3))  
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.zeros(5, dtype=int)  
print(arr) 

## 3. np.ones()

In [ ]:
Create an array filled with 1s.
Syntax: np.ones(shape, dtype=float)

In [4]:
ar1 = np.ones((3, 2))  
print(ar1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


## 4. np.arange()

In [ ]:
Create evenly spaced values within a range.
Syntax: np.arange(start, stop, step)

In [5]:
arr = np.arange(0, 10, 2)  
print(arr)

[0 2 4 6 8]


In [6]:
arr = np.arange(5, 0, -1)  
print(arr)

[5 4 3 2 1]


## 5. np.linspace()

In [ ]:
Create linearly spaced values (fixed number of points).
Syntax: np.linspace(start, stop, num=50)

In [ ]:
arr = np.linspace(0, 1, 5)   #5 points between 0 and 1 (inclusive)
print(arr)

## 6. np.random.rand()

In [ ]:
Create an array of random floats between 0 and 1.
Syntax: np.random.rand(d0, d1, ..., dn)

In [7]:
arr = np.random.rand(2, 2)  
print(arr)

[[0.84884575 0.8568548 ]
 [0.08607903 0.4678061 ]]


In [8]:
arr = np.random.rand(2, 2, 2)  
print(arr.shape) 

(2, 2, 2)


## 7. np.full()

In [ ]:
>> Create an array filled with a specific value.
>> Syntax: np.full(shape, fill_value, dtype=None)

In [2]:
import numpy as np

In [3]:
a1=np.full((2,2),11)
a1

array([[11, 11],
       [11, 11]])

In [9]:
arr = np.full((3, 3), 5)  
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [6]:
ara = np.full(4, "A", dtype=str)  
print(ara)

['A' 'A' 'A' 'A']


In [16]:
ara = np.full(4, "AA", dtype="U6")  
print(ara)

['AA' 'AA' 'AA' 'AA']


## 8.np.eye() / np.identity()

In [ ]:
>> Create an identity matrix (1s on the diagonal, 0s elsewhere).
>> Syntax: 
    np.eye(N, k=0)

In [4]:
asa=np.eye(4)
asa

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
arr = np.eye(3)  
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
arr = np.eye(3, k=1)  
print(arr)  #Offset diagonal (k=1):

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [14]:
arr = np.eye(3, k=-1)  
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


## 9. np.diag()

In [ ]:
Create a diagonal matrix or extract the diagonal from a 2D array.
Syntax: np.diag(v)

In [6]:
#[11,22,33,44]
az=np.diag([11,22,33,44])
az

array([[11,  0,  0,  0],
       [ 0, 22,  0,  0],
       [ 0,  0, 33,  0],
       [ 0,  0,  0, 44]])

In [ ]:
arr = np.diag([1, 2, 3])  
print(arr)

## 10. np.random.randint()

In [ ]:
Generate random integers within a range.
Syntax: np.random.randint(low, high, size_array)

In [17]:
arr = np.random.randint(1, 10, 5)  
print(arr)

[2 6 2 9 3]


In [18]:
arr = np.random.randint(10, 20, (2, 2))  
print(arr) 

[[10 11]
 [12 16]]


# 2. Array Manipulation

In [ ]:
(Functions to modify array shape, structure, and content)

In [2]:
import numpy as np

## 2.1 reshape()

In [ ]:
>> Change array dimensions without altering data.
Syntax: 
    arr.reshape(new_shape)

In [15]:
arz=np.arange(12)
print(arz)
print("dimension of array before reshape",arz.ndim)
print("size of array before reshape", arz.size)
reshaped1=arz.reshape(4,3)
print("*"*20)
print(reshaped1)
print(reshaped1.ndim)  
print(reshaped1.size)    #4*3, 3*4, 6*2

[ 0  1  2  3  4  5  6  7  8  9 10 11]
dimension of array before reshape 1
size of array before reshape 12
********************
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2
12


In [19]:
arr11 = np.arange(6)  #1D to 2D
reshaped = arr11.reshape(2, 3) #3*2...6*1  
print(arr11)
print(reshaped)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


## 2.2 resize()

In [ ]:
>> Change array size (repeats elements if new size is larger).
Syntax: np.resize(arr, new_shape)

In [16]:
a2=np.array([99,88,77])
a21=np.resize(a2, (3,2))
a21

array([[99, 88],
       [77, 99],
       [88, 77]])

In [22]:
arr = np.array([1, 2, 3])  
resized = np.resize(arr, (5,))  # Repeats elements  
print(resized)

[1 2 3 1 2]


In [10]:
arr = np.array([[1, 2], [3, 4]])  
resized = np.resize(arr, (3, 3))  # Adds new rows 
print(arr)
print(resized) 

[[1 2]
 [3 4]]
[[1 2 3]
 [4 1 2]
 [3 4 1]]


## 2.3 flatten() 


In [ ]:
>>> to Convert N-dimensional arrays to 1D.
[[1,2,3],[5,45,67]]>>>>[1,2,3,5,45,67]

In [ ]:
flatten(): Returns a copy.


In [17]:
arr = np.array([[1, 2], [3, 4]])  
flat = arr.flatten()  
#flat[0] = 99  # Original array remains unchanged  
print(arr)
print("*"*20)
print(flat)

[[1 2]
 [3 4]]
********************
[1 2 3 4]


## 2.3 transpose()

In [ ]:
>> Reverse or permute array axes.
Syntax: 
    arr.transpose() or arr.T

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  
transposed = arr.T  #rows will be converted into columns and columns will be converted into rows
print(arr)
print("#"*20)
print(transposed)  

[[1 2 3]
 [4 5 6]]
####################
[[1 4]
 [2 5]
 [3 6]]


## 2.4 concatenate()

In [ ]:
>> Join arrays along an existing axis.
Syntax: np.concatenate((arr1, arr2), axis=0)

In [19]:
# Along rows (axis=0):
arr1 = np.array([[1, 2], [3, 4]])  
arr2 = np.array([[5, 6]])

print("before concatenate fnction")

result = np.concatenate((arr1, arr2), axis=0)
print(arr1)
print("*"*15)
print(arr2)
print("*"*15)
print(result)

before concatenate fnction
[[1 2]
 [3 4]]
***************
[[5 6]]
***************
[[1 2]
 [3 4]
 [5 6]]


In [22]:
#Along columns (axis=1)
arr1 = np.array([[1], [2]])  
arr2 = np.array([[3], [4]])  
result = np.concatenate((arr1, arr2), axis=1)  
print("*"*15)
print(arr1)
print("*"*15)
print(arr2)
print("*"*15)
print(result)

***************
[[1]
 [2]]
***************
[[3]
 [4]]
***************
[[1 3]
 [2 4]]


## 2.5 append()

In [ ]:
>> Add values to the end of an array.
Syntax: np.append(arr, values, axis=None)

In [23]:
arr1 = np.array([1, 2, 3])  
new_arr = np.append(arr1, [4, 5])  
print(new_arr)

[1 2 3 4 5]


## 2.6 insert()

In [ ]:
>>> Insert values at a specific position.
Syntax: np.insert(arr, index, values, axis=None)

In [31]:
arr = np.array([10, 20, 30])  
new_arr = np.insert(arr, 1, 99)  # Insert 99 at index 1  
print(new_arr) 

[10 99 20 30]


In [25]:
array1=np.arange(10)
nw=np.insert(array1, 3, 300)
nw

array([  0,   1,   2, 300,   3,   4,   5,   6,   7,   8,   9])

## 2.7 delete()

In [ ]:
>> Remove elements along an axis.
Syntax: 
    np.delete(arr, index, axis=None)

In [32]:
arr = np.array([1, 2, 3, 4])  
new_arr = np.delete(arr, 1)  # Remove index 1  
print(new_arr)

[1 3 4]


## 2.8 sort()

In [ ]:
>>> Sort array elements.
>>> Syntax: 
    np.sort(arr)

In [28]:
arr = np.array([3, 1, 2])  
sorted_arr = np.sort(arr, axis=-1)  
print(sorted_arr)

[1 2 3]


# 3. Mathematical Operations

In [ ]:
>> Functions for element-wise, statistical, and algebraic operations

## 3.1 np.sum()

In [ ]:
>>> Compute the sum of array elements.
>>> Syntax:
    np.sum(arr, axis=None)

In [34]:
arr = np.array([1, 2, 3])  
total = np.sum(arr)  
print(total)

6


In [29]:
arr = np.array([[1, 2], [3, 4]])  
col_sum = np.sum(arr, axis=0)  
print(arr)
print("*"*10)
print(col_sum)

[[1 2]
 [3 4]]
**********
[4 6]


In [37]:
arr = np.array([[1, 2], [3, 4]])  
col_sum = np.sum(arr, axis=1)  
print(arr)
print(col_sum)

[[1 2]
 [3 4]]
[3 7]


## 3.2 np.mean()

In [ ]:
>>> Compute the arithmetic mean (average).
>>>> Syntax:
    np.mean(arr, axis=None)

In [39]:
arr = np.array([10, 20, 30])  #Mean of all elements:
avg = np.mean(arr)
avg

20.0

In [40]:
arr = np.array([[1, 2], [3, 4]])  
row_avg = np.mean(arr, axis=1)  
print(row_avg)

[1.5 3.5]


## 3.3 np.max() & np.min()

In [ ]:
Find the maximum or minimum value.
Syntax: np.max(arr)

In [30]:
arr = np.array([5, 2, 9, 1])  
print(np.max(arr))  # Output: 9  
print(np.min(arr))

9
1


## 3.4 np.std() & np.var()

In [ ]:
>> Compute standard deviation or variance.
Syntax: 
    np.std(arr) / np.var(arr)

In [42]:
arr = np.array([1, 2, 3, 4])  #Standard deviation:
print(np.std(arr))

1.118033988749895


In [43]:
arr = np.array([[2, 4], [6, 8]])  #Variance of rows
row_var = np.var(arr, axis=1)  
print(row_var)

[1. 1.]


## 3.5 np.sqrt() & np.power()

In [ ]:
Compute square roots or raise elements to a power.
Syntax: np.sqrt(arr) / np.power(arr, exponent)

In [44]:
arr = np.array([4, 9, 16])  
print(np.sqrt(arr))

[2. 3. 4.]


In [45]:
arr = np.array([2, 3])  
print(np.power(arr, 3))

[ 8 27]


## 3.6 np.dot()

In [ ]:
Compute the dot product of two arrays.
Syntax: np.dot(a, b)

In [46]:
a = np.array([1, 2])  
b = np.array([3, 4])  
print(np.dot(a, b))  #(1*3 + 2*4)  

11


## 3.7 np.add(), np.subtract(), np.multiply(), np.divide()

In [ ]:
Element-wise arithmetic operations.

Syntax: np.add(a, b)

In [47]:
a = np.array([1, 2])  
b = np.array([3, 4])  
print(np.add(a, b)) 

[4 6]


In [33]:
a = np.array([[5, 6], [7, 8]])  
b = np.array([[1, 2], [3, 4]])
print(a)
print("-"*10)
print(b)
print("-"*10)
print(np.subtract(a, b))

[[5 6]
 [7 8]]
----------
[[1 2]
 [3 4]]
----------
[[4 4]
 [4 4]]


In [49]:
a = np.array([1, 2])  
b = np.array([3, 4])  
print(np.multiply(a, b))

[3 8]


In [50]:
a = np.array([1, 2])  
b = np.array([3, 4])  
print(np.divide(a, b))

[0.33333333 0.5       ]


## 3.8 np.round()

In [ ]:
>> Round elements to the nearest integer.
Syntax: np.round(arr, decimals=0)

In [51]:
arr = np.array([2.3, 4.7, 5.5])  #Round to nearest integer
print(np.round(arr))

[2. 5. 6.]


In [52]:
arr = np.array([3.1415, 2.718])  #Round to 1 decimal
print(np.round(arr, 1))

[3.1 2.7]


# 5. Logical & Indexing

In [ ]:
>> Return indices or values based on a condition.
>> Returns indices where condition is True.

In [ ]:
#np.where

In [55]:
arr = np.array([2, 6, 1, 8, 3])  
result = np.where(arr > 5)  
print(result) # we will get index numbers

(array([1, 3], dtype=int64),)


In [53]:
arr = np.array([5, 10, 15, 20, 25])
result = np.where(arr > 15, 100, 0)  
print(result) 

[  0   0   0 100 100]


# np.any()

In [ ]:

Check if any element satisfies a condition. output is in True or False

In [35]:
arr = np.array([1, -2, 3, 4])  
print(np.any(arr < 0))

True


# np.unique()

In [ ]:
#np.unique()
Extract unique elements and optionally count them


In [57]:
arr = np.array([2, 2, 3, 5, 3, 5])  
unique_values = np.unique(arr)  
print(unique_values)

[2 3 5]


In [58]:
unique, counts = np.unique(arr, return_counts=True)
print(unique)
print(counts) 

[2 3 5]
[2 2 2]
