In [ ]:
-numpy array is collection of homogeneous datatypes
-numpy is faster than list
-numpy array

In [ ]:
!pip install numpy

In [4]:
pip install numpy


In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd

In [1]:
import numpy as np

# how to create numpy array

In [5]:
array1=np.array([1,3,4,5])
print(array1)
array12=np.zeros((3,2))
print(array12)

[1 3 4 5]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
array11=np.array([11,22,33,44])
type(array11)
array11.dtype

dtype('int32')

In [5]:
print(type(array1))

<class 'numpy.ndarray'>


In [7]:
array1.dtype

dtype('int32')

## various functions to create arrays

## zeros()

In [ ]:
Create an array filled with zeros.
>> np.zeros()


In [8]:
a=np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
a11=np.zeros((2,2))
a11

array([[0., 0.],
       [0., 0.]])

## ones()

In [ ]:
>> Create an array filled with ones.
np.ones()


In [8]:
one1=np.ones((2,2))
one1.dtype

dtype('float64')

In [9]:
ab=np.ones((3, 2))
ab

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## np.arange()

In [ ]:
>> Create array of equally spaced values.
np.arange()


In [6]:
aa=np.arange(0, 10, 2)
aa

array([0, 2, 4, 6, 8])

In [10]:
a1=np.arange(10,20,3)
a1

array([10, 13, 16, 19])

## np.linspace()

In [ ]:
>> Create linearly spaced values.
np.linspace()
10>>>20....12

In [11]:
s1=np.linspace(10,20,12)
s1

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909, 20.        ])

In [11]:
x=np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## np.random.rand()

In [ ]:
>> Generate random values (0 to 1).
np.random.rand()
>> to create array of having numbers between o to 1

In [12]:
bb1=np.random.rand(2,3)
bb1

array([[0.54527607, 0.69129111, 0.59635576],
       [0.46532202, 0.90900278, 0.2988599 ]])

In [12]:
bb=np.random.rand(2, 2)
bb

array([[0.65539101, 0.68724475],
       [0.23582696, 0.59737571]])

## np.random.randint()

In [ ]:
>> to create array having random elements of certain range
>> np.random.randint(start,end,array_size)

In [13]:
np.random.randint(1,10,(2,2))

array([[7, 4],
       [3, 8]])

In [20]:
aaa=np.random.randint(10,100,(3,3))
aaa

array([[79, 22, 50],
       [53, 39, 25],
       [70, 28, 24]])

# Type casting in Numpy Array

In [18]:
import numpy as np

In [ ]:
>> changing the data type of element of numpy array

In [20]:
array1 =np.array([2,4,5,6])
array1.dtype

dtype('int32')

In [21]:
aa=np.array([15,353,454],dtype=complex)
print(aa)
print(aa.dtype)

[ 15.+0.j 353.+0.j 454.+0.j]
complex128


In [7]:
array1 =np.array([2,4,5,6],dtype=float)
array1.dtype

dtype('float64')

In [24]:
array1 =np.array([2,4,5.5,6],dtype = int)
print(array1)
print(array1.dtype)

[2 4 5 6]
int32


In [26]:
array1 =np.array([2,4,5.5,6],dtype = complex)
print(type(array1))
print(array1)
print(array1.dtype)

<class 'numpy.ndarray'>
[2. +0.j 4. +0.j 5.5+0.j 6. +0.j]
complex128


In [27]:
array1 =np.array([2,4,5.5,6],dtype = str)
print(type(array1))
print(array1)
print(array1.dtype)

<class 'numpy.ndarray'>
['2' '4' '5.5' '6']
<U3


In [28]:
array1 =np.array([2,4,5.5,6],dtype = float)
print(type(array1))
print(array1)
print(array1.dtype)

<class 'numpy.ndarray'>
[2.  4.  5.5 6. ]
float64


In [30]:
array1 =np.array([2,4,5.5,6],dtype = object)
print(type(array1))
print(array1)
print(array1.dtype)

<class 'numpy.ndarray'>
[2 4 5.5 6]
object


In [31]:
array1 =np.array([2,4+5j,5.5,6],dtype = float)
print(type(array1))
print(array1)
print(array1.dtype)

TypeError: can't convert complex to float

In [32]:
array1 =np.array([2,4+5j,5.5,6],dtype = int)
print(type(array1))
print(array1)
print(array1.dtype)

TypeError: can't convert complex to int

int >> float
float >> int
int >> complex,str
FLOAT >> complex,str
complex !!>> int,float is not possible

# Dimensions in numpy array

### 1. 0-D array
to check the dimension of arry >>>> array.ndim

In [ ]:
# A 0D array represents a single value.

In [23]:
z1=np.array(12)
print(z1.ndim)

0


In [34]:
a1 = np.array(30)
print(a1)
print(a1.ndim) #array.ndim

30
0


In [38]:
a1 = np.array(30)
print("Number of dimension of an array : ",a1.ndim)

Number of dimension of an array :  0


### 2. 1 -Dimentional Array

In [ ]:
>> It is a collection of multiple 0-dimentional arrays

In [8]:
array2 = np.array([5,4,2,7,8,6])
print("Array is : ",array2)
print("Number of dimension of an array : ",array2.ndim)

Array is :  [5 4 2 7 8 6]
Number of dimension of an array :  1


In [24]:
za=np.array([22,33,44,55])
print(za)
print(za.ndim)

[22 33 44 55]
1


In [40]:
array2 = np.array((5,4,2,7,8,6))
print("Array is : ",array2)
print("Number of dimension of an array : ",array2.ndim)

Array is :  [5 4 2 7 8 6]
Number of dimension of an array :  1


In [41]:
array2 = np.array([2])
print("Array is : ",array2)
print("Number of dimension of an array : ",array2.ndim)

Array is :  [2]
Number of dimension of an array :  1


In [45]:
array2 = np.array((2,))
print("Array is : ",array2)
print("Number of dimension of an array : ",array2.ndim)

Array is :  [2]
Number of dimension of an array :  1


## 3. 2-Dimentional Array

In [ ]:
>> It is collection of multiple 1-dimentional array

In [25]:
ast=np.array([[1,2,3],[4,5,6]])
ast

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
array2 = np.array([[5,4,2,7,8,6],[4,6,8,7,8,9]])
print("Array is : ",array2)
print("Number of dimension of an array : ",array2.ndim)

Array is :  [[5 4 2 7 8 6]
 [4 6 8 7 8 9]]
Number of dimension of an array :  2


In [51]:
array2 = np.array([[5,4,2,7,8,6],[4,6,8,7,8,9],[3,5,4,1,2,3]])
print("Array is :\n",array2)
print("Number of dimension of an array : ",array2.ndim)

Array is :
 [[5 4 2 7 8 6]
 [4 6 8 7 8 9]
 [3 5 4 1 2 3]]
Number of dimension of an array :  2


In [26]:
array2 = np.array([[5,4,2,7],[4,6,8,7,8,9],[3,5,4,1,2,3]])
print("Array is :\n",array2)
print("Number of dimension of an array : ",array2.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 4. 3 -Dimentional array

In [ ]:
>> It is collection of multiple 2-D arrays

In [27]:
a111=np.array([[[11,22,33],[44,55,66]]])
a111.ndim

3

In [28]:
array2 = np.array([[[5,4,2,7,8,6],[3,5,4,1,2,3]]])
print("Array is :\n",array2)
print("Number of dimension of an array : ",array2.ndim)

Array is :
 [[[5 4 2 7 8 6]
  [3 5 4 1 2 3]]]
Number of dimension of an array :  3


In [56]:
array3 = np.array([[[2,3,4],[10,20,30],[100,200,300]],[[20,30,40],[50,40,60],[500,400,600]]])
print("Array is :\n",array3)
print("Number of dimension of an array : ",array3.ndim)

Array is :
 [[[  2   3   4]
  [ 10  20  30]
  [100 200 300]]

 [[ 20  30  40]
  [ 50  40  60]
  [500 400 600]]]
Number of dimension of an array :  3


# Access array items using indexing and slicing

In [1]:
list1 =[4,5,6,7,8,9]
print(list1[0])
print(list1[2])

4
6


In [61]:
list1 =[4,5,6,7,8,9]
list1[1:5:2]

[5, 7]

In [ ]:
syntax:
array[start_index:end_index:step_size]

In [31]:
array1 = np.array([5,4,6,7,8,9,5,2])
array1[0]
array1[-1]
array1[]

array([4, 7, 9, 2])

In [63]:
array1 = np.array([5,4,6,7,8,9,5,2])
array1[5]

9

In [65]:
array1 = np.array([5,4,6,7,8,9,5,2])
array1[1:6:2]

array([4, 7, 9])

In [67]:
array1 = np.array([5,4,6,7,8,9,5,2])
array1[::-1]

array([2, 5, 9, 8, 7, 6, 4, 5])

In [68]:
array1 = np.array([5,4,6,7,8,9,5,2])
array1[-3]

9

In [32]:
array2 = np.array([[5,4,2,7,8,6],[31,51,41,11,21,36]])
print(array2)
print(array2.ndim)

[[ 5  4  2  7  8  6]
 [31 51 41 11 21 36]]
2


In [36]:
array2[0][1:]

array([4, 2, 7, 8, 6])

In [7]:
array2[1][0]

31

In [9]:
array2[0][0]

5

In [75]:
array2[1][-1]

36

In [38]:
array21 = np.array([[[5,4,2,7,8,6],[31,51,41,11,21,36]],[[90,40,20,70,80,60],[1,5,4,9,2,3]]])
print(array21)

[[[ 5  4  2  7  8  6]
  [31 51 41 11 21 36]]

 [[90 40 20 70 80 60]
  [ 1  5  4  9  2  3]]]


In [42]:
array21[0][0]

array([5, 4, 2, 7, 8, 6])

In [44]:
array21[1][1][2:]

array([4, 9, 2, 3])

In [87]:
array21[1][0,3] 

70

In [89]:
array2[1,0,3]

70

In [12]:
array2 = np.array([[[5,4,2,7,8,6],[31,51,41,11,21,36]],[[90,40,20,70,80,60],[1,5,4,9,2,3]]])
print(array2)

[[[ 5  4  2  7  8  6]
  [31 51 41 11 21 36]]

 [[90 40 20 70 80 60]
  [ 1  5  4  9  2  3]]]


In [115]:
array2[0,0]

array([5, 4, 2, 7, 8, 6])

In [13]:
array2[0,0,0]

5

In [116]:
array2[:,0]

array([[ 5,  4,  2,  7,  8,  6],
       [90, 40, 20, 70, 80, 60]])

In [99]:
array4 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]])
print(array4)
print(array4.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]]
3


In [111]:
array2 = np.array([[[5,4,2,7,8,6],[31,51,41,11,21,36]],[[90,40,20,70,80,60],[1,5,4,9,2,3]]])
print(array2)

[[[ 5  4  2  7  8  6]
  [31 51 41 11 21 36]]

 [[90 40 20 70 80 60]
  [ 1  5  4  9  2  3]]]


In [113]:
array2[:]

array([[[ 5,  4,  2,  7,  8,  6],
        [31, 51, 41, 11, 21, 36]],

       [[90, 40, 20, 70, 80, 60],
        [ 1,  5,  4,  9,  2,  3]]])

In [117]:
array2[0][0,1:3]

array([4, 2])

In [121]:
array2[1,0,:]

array([90, 40, 20, 70, 80, 60])

In [123]:
array2[1,0,::-1]

array([60, 80, 70, 20, 40, 90])

In [127]:
array2[1,0,::2]

array([90, 20, 80])

In [128]:
array2 = np.array([[[5,4,2],[31,51,41],[11,21,36]],[[90,40,20],[70,80,60],[9,2,3]]])
print(array2)

[[[ 5  4  2]
  [31 51 41]
  [11 21 36]]

 [[90 40 20]
  [70 80 60]
  [ 9  2  3]]]


In [147]:
array2[:,1:,1:]

array([[[51, 41],
        [21, 36]],

       [[80, 60],
        [ 2,  3]]])

In [148]:
array2[0,0::2,1:]

array([[ 4,  2],
       [21, 36]])

In [130]:
array2[0,0,1:]

array([4, 2])

In [131]:
array2[1,1,1:]

array([80, 60])

In [138]:
array2[0,1:,1:]

array([[51, 41],
       [21, 36]])